"""Configs for NbodyX codes."""

_NBODY6_KZ = {
    1: "COMMON save unit 1 (=1: 'touch STOP'; =2: every 100*NMAX steps).",
    2: "COMMON save unit 2 (=1: at output; =2: restart if DE/E > 5*QE).",
    3: "Basic data unit 3 at output time (unformatted, frequency NFIX; =1/2: standard and tail; =3: tail only; >3: cluster + tail).",
    4: "Binary diagnostics on unit 4 (# threshold levels = KZ(4) < 10); (suppressed in input.f & ksint.f); new usage: number of NS & BH on unit #4; >1: BH mass histogram.",
    5: "Initial conditions (#22 =0; =0: uniform & isotropic sphere); =1: Plummer; =2: two Plummer models in orbit, extra input; =3: massive perturber and planetesimal disk, extra input; =4: massive initial binary, extra input: A, E, M1, M2; =5: Jaffe model; >=6: Zhao BH cusp model, extra input if #24 < 0: ZMH, RCUT.",
    6: "Soft & regularized binaries & individual bodies at main output; =1: soft & regularized binaries on unit 6; =2: regularized binaries only; >2: individual bodies (loop from 1 to KZ(6)).",
    7: "Lagrangian radii (>0: RSCALE; =2, 3, 4: output units 6, 7); >=2: half-mass radii of 50% mass, also 1% heavies, unit 6; >=2: Lagrangian radii for two mass groups on unit 31 & 32; >=2: geometric radii for three mass groups on unit 6; =5: density, rms velocity & mean mass on unit 26, 27 & 36; =6: pairwise values of mean mass and radii on unit 28.",
    8: "Primordial binaries (=1 & >=3 routine BINPOP; >=3: SWEEP; =4: Kroupa 1995 period distribution; >4: standard setup using RANGE & SEMI0).",
    9: "Binary output  (=1, 2, 3 in BINDAT): =1: regularized binaries on OUT9; >1: hierarchical systems on HIDAT (NMERGE > 0); =2: regularized and soft binaries (unit #19); =3: soft binaries only on #19.",
    10: "Diagnostic KS output (>0: begin KS; >1: end; >=3: each step).",
    11: "Algorithmic Chain regularization and post-Newtonian (NBODY7). non-zero: PN for unpert KS or re-init ARChain (ksint.f); > 0: addition of initial BHs (binary/singles; scale.f); = -1: standard case of subsystem for ARChain (ksint.f); < -1: ARChain restricted to BH binary components (ksint.f).",
    12: "HR diagnostics of evolving stars (> 0; interval DTPLOT); =2: input of stellar parameters on fort.12 (routine INSTAR).",
    13: "Interstellar clouds (=1: constant velocity; >1: Gaussian).",
    14: "External force (=1: standard tidal field; =2: point-mass galaxy; =3: point-mass + bulge + disk + halo + Plummer; =4: Plummer).",
    15: "Triple, quad, chain (#30 > 0) or merger search (>1: more output).",
    16: "Updating of regularization parameters (>0: RMIN, DTMIN & ECLOSE); >1: RMIN expression based on core radius; >2: modify RMIN for GPERT > 0.05 or < 0.002 in chain.",
    17: "Modification of ETAI, ETAR (>=1) and ETAU (>1) by tolerance QE.",
    18: "Hierarchical systems (=1: diagnostics; =2: primordial; =3: both).",
    19: "Mass loss (=1: old supernova scheme; =3: Eggleton, Tout & Hurley; >3: extra diagnostics).",
    20: "Initial mass function (=0: Salpeter type using ALPHAS; =1: Scalo; =2, 4: Kroupa 1993; =3, 5: Eggleton; > 1: primordial binaries; =6, 7: Kroupa 2001; binary correlated m1/m2, also brown dwarfs. Note: Use PARAMETER (MAXM=1) for setting BODY(1) = BODY10). KGT93 (Kroupa, Gilmore & Tout 1993) not recommended.",
    21: "Extra output (>0: MODEL #, TCOMP, DMIN, AMIN; >1: NESC by JACOBI).",
    22: "Initial m, r, v on #10 (=1: output; >=2: input; >2: no scaling; =2: m, r, v on #10 in any units; scaled to standard units; Note: choose #20 = 0 to avoid Salpeter IMF with scaling; =3: no scaling of input read on fort.10; =4: input from mcluster.c (no scaling; binaries if NBIN0 >0); =-1: astrophysical input (M_sun, km/s, pc) on unit #10).",
    23: "Escaper removal (>1: diagnostics in file ESC with V_inf in km/s); >=3: initialization & integration of tidal tail.",
    24: "Initial conditions for subsystem (M,X,V routine SCALE; KZ(24)= #); <0: ZMH & RCUT (N-body units) Zhao model (#5>=6).",
    25: "Velocity kicks for white dwarfs (=1: type 11 & 12; >1: all WDs).",
    26: "Slow-down of two-body motion (>=1: KS; >=2: chain; =3: rectify).",
    27: "Tidal effects (=1: sequential; =2: chaos; =3: GR energy loss); =-1: collision detector, no coalescence, #13 < 0.",
    28: "GR radiation for NS & BH binaries (with #19 = 3; choice of #27); =4 and #27 = 3: neutron star capture (instar.f).",
    29: "Boundary reflection for hot system (suppressed).",
    30: "Multiple regularization (=1: all; >1: BEGIN/END; >2: each step); =-1: CHAIN only; =-2: TRIPLE & QUAD only.",
    31: "Centre of mass correction after ADJUST (don't use with #23 = 0).",
    32: "Increase output intervals & SMAX based on single particle energy.",
    33: "Histograms at main output (>=1: STEP; =2: STEPR, NBHIST & BINARY).",
    34: "Roche-lobe overflow (=1: ROCHE & SYNCH; =2: ROCHE & BSE synch).",
    35: "Time offset (global time from TTOT = TIME + TOFF; offset = 100).",
    36: "Step reduction for hierarchical systems (suppressed).",
    37: "Neighbour additions in CHECKL (>0: high-velocity; >1: all types).",
    38: "Force polynomial corrections (=0: standard, no corrections; =1: all gains & losses included; =2: small FREG change skipped; =3: fast neighbour loss only).",
    39: "No unique density centre (skips velocity modification of RS(I)).",
    40: "Neighbour number control (=1: increase if <NNB>  <  NNBMAX/2); >=2: fine-tuning at NNBMAX/5; =3: reduction of NNBMAX",
    41: "Pre-mainsequence stellar evolution (only solar metallicity).",
    42: "Kozai diagnostics on fort.42 (=1: frequency 100 & EMAX > 0.99)",
    43: "Small velocity kick after GR coalescence (=1, =3; NBODY7 only), =2: BH accretion of disrupted star, KSTAR >= 10. >=2: disrupted star ejected as ghost, KSTAR < 10.",
    44: "Plotting file for main cluster parameters on fort.56 (OUTPUT).",
    45: "Plotting file for BH (NAME = 1 or 2) on unit 45 (routine BHPLOT); primordial BH defined by INSTAR; membership = KZ(24); =1: plotting output for BH (one or two); >1: BH in KS binary (NCH = 0, unit 45); >2: KS & perturber diagnostics (E > 0.9, EX > 0.9); >3: output for 2nd innermost BH orbit (unit #49); <0: strong three-body events (impact.f, unit #49).",
    46: "Reserved for data analysis project on NBODY6++.",
    47: "Reserved for data analysis project on NBODY6++.",
    48: "Three-body stability comparison (Valtonen & Mardling 2008 fort.88).",
    49: "Post-Newtonian perturbations included in KS (dir Block).",
    50: "Not used.",
}

_NBODY6PPGPU_BEIJING_KZ = {
    1: "Save COMMON to file comm.1 = 1: at end of run or when dummy file STOP is created = 2: every 100*NMAX steps",
    2: "Save COMMON to file comm.2 = 1: save at output time = 2: save at output time and restart simulation if energy error DE/E > 5*QE",
    3: "Save basic data to file conf.3 at output time (unformatted)",
    4: "(Suppressed) Binary diagnostics on bdat.4 (# = threshold levels <10)",
    5: "Initial conditions of the particle distribution, needs KZ(22)=0 = 0: uniform & isotropic sphere = 1: Plummer random generation = 2: two Plummer models in orbit (extra input) = 3: massive perturber and planetesimal disk (each pariticle has circular orbit, constant separation along radial direction between each neighbor and random phase) (extra input) = 4: massive initial binary (extra input) = 5: Jaffe model (extra input) ≥ 6: Zhao BH cusp model (extra input if KZ(24)<0)",
    6: "Output of significant and regularized binaries at main output (bodies.f) = 1: output regularized and significant binaries (|E|>0.1 ECLOSE) = 2: output regularized binaries only = 3: output significant binaries at output time and regularized binaries with time interval DELTAT = 4: output of regularized binaries only at output time",
    7: "Determine Lagrangian radii and average mass, particle counters, average velocity, velocity dispersion, rotational velocity within Lagrangian radii (lagr.f) = 1: Get actual value of half mass radius RSCALE by using current total mass ≥ 2: Output data at main output and lagr.7 ≥ 6: Output Lagrangian radii for two mass groups at lagr.31 and lagr.32 (lagr2.f; based on KZ(5)=1,2; cost is O(N2)) —- methods: = 2, 4: Lagrangian radii calculated by initial total mass = 3, ≥ 5: Lagrangian radii calculated by current total mass (The single/K.S-binary Lagrangian radii are still calculated by initial single/binary total mass) = 2, 3: All parameters are averaged within the shell between two Lagrangian radii neighbors ≥ 4: All parameters are averaged from center to each Lagrangian radius",
    8: "Primordial binaries initialization and output (binpop.f) —- Initialization: = 0: No primordial binaries = 1, ≥ 3: generate primordial binaries based on KZ(41) and KZ(42) (binpop.F) = 2: Input primordial binaries from first 2×NBIN0 lines of dat.10 —- Output: > 0: Save information of primordial binary that change member in pbin.18; binary diagnostics at main output (binout.f) ≥ 2: Output KS binary in bdat.9, soft binary in bwdat.19 at output time",
    9: "Binary diagnostics = 1, 3: Output diagnostics for the hardest binary below ECLOSE in hbin.39 (adjust.f) ≥ 2: Output binary evolution stages in binev.17 (binev.f) ≥ 3: Output binary with degenerate stars in degen.4 (degen.f)",
    10: "K.S. regularization diagnostics at main output > 0: Output new K.S. information > 1: Output end K.S. information ≥ 3: Output each integrating step information",
    11: "(Suppressed)",
    12: "> 0: HR diagnostics of evolving stars with output time interval DTPLOT in sse.83 (single star) and bse.82 (K.S. binary) = −1: used if KZ(19)= 0 (see details in KZ(19) description)",
    13: "Interstellar clouds = 1: constant velocity for new cloud > 2: Gaussian velocity for new cloud",
    14: "External tidal force = 1: standard solar neighbor tidal field = 2: point-mass galaxy with circular orbit (extra input) = 3: point-mass + disk + halo + Plummer (extra input) = 4: Plummer model (extra input) = 5: Milky-Way potential (extra input) based on Galpy package (Bovy, 2015) Note: Namelist input has all fields for values 2,3,4, but user must take care to put proper value",
    15: "Triple, quad, chain and merger search ≥ 1: Switch on triple, quad, chain (KZ(30)>0) and merger search (impact.f) ≥ 2: Diagnostics at main output at begin and end of triple, quad ≥ 3: Save first five outer orbits every half period of wide quadruple before merger and stable quadruples accepted for merger in quastab.89",
    16: "Auto-adjustment of regularization parameters ≥ 1: Adjust RMIN, DTMIN & ECLOSE every DTADJ time ≥ 3: modify RMIN for GPERT > 0.05 or < 0.002 in chain; output diagnostics at kscrit.77",
    17: "Auto-adjustment of ETAI, ETAR and ETAU by tolerance QE every DTADJ time (check.f) ≥ 1: Adjust ETAI, ETAR ≥ 2: Adjust ETAU",
    18: "Hierarchical systems = 1, 3: diagnostics (hiarch.f) ≥ 2: Initialize primordial stable triples, number is NHI0 (hipop.F) ≥ 4: Data bank of stable triple, quad in hidat.87 (hidat.f)",
    19: "Stellar evolution and mass loss scheme = 0: if KZ(12)= −1, the output data will keep the input data unit if KZ(22)= 2 − 4 or N-body units if KZ(22)= 6 − 10 = 1, 2: supernova scheme ≥ 3: Eggleton, Tout & Hurley ≥ 5: extra diagnostics (mdot.F) = 2, 4: input stellar parameters from datsev.21; read by (instar.f): N lines of (MI, KW, M0, EPOCH1, OSPIN, MC); N is the number of particles in datsev.21 and dat.10 and has to be set accordingly in Nbody input file. MI: current mass KW: stellar type M0: initial mass EPOCH1: evolved age of star (AGE = − EPOCH1 [Myr]) OSPIN: angular velocity of star (may be zero if not relevant) MC: core mass (may be zero if not relevant) = 4: Take input data from other code (e.g. Monte Carlo); first line of datsev.21 in this case read by start.F to establish desired scaling: 1 line of (TMOC,NZERO,RBAR,ZMBAR,TSTAR) (these data override data read or computed by Nbody before) TMOC: Cluster age in Myr NZERO: Particle number at zero cluster age RBAR, ZMBAR: scaling for radii and average TSTAR: 1Myr in model units;",
    20: "Initial mass functions, need KZ(22)=0 or 9: = 0: self-defined power-law mass function using ALPHAS (data.F) = 1: Miller-Scalo-(1979) IMF (imf.f) = 2, 4: KTG (1993) IMF (imf2.f) = 3, 5: Eggleton-IMF (imf2.f) = 6, 7: Kroupa(2001) (imf2.f), extended to Brown Dwarf regime (imfbd.f) —- Primordial binary mass = 2, 6: random pairing (imf2.f) = 3, 4, 5, 7: binary mass ratio corrected by (m1/m2)′ = (m1/m2)0.4 + constant (Eggleton, imf2.f) = 8: binary mass ratio q = m1/m2 (m2 ≤ m1) use distribtution 0.6q−0.4 (Kouwenhoven)",
    21: "Extra diagnostics information at main output every DELTAT interval (output.F) ≥ 1: output NRUN, MODEL, TCOMP, TRC, DMIN, AMIN, RMAX, RSMIN, NEFF ≥ 2: Number of escapers NESC at main output will be counted by Jacobi escape criterion (cost is O(N2), jacobi.f)",
    22: "Initialization of basic particle data mass, position and velocity (data.F) —- Initialization with internal method = 0, 1: Initial position, velocity based on KZ(5), initial mass based on KZ(20) = 1: write initial conditions in dat.10 (scale.F) —- Initialization by reading data from dat.10 = 2: input through NBODY-format (7 parameters each line: mass, position(1:3), velocity(1:3)) = 3: input through Tree-format (data.F) = 4: input through Starlab-format = 6: input through NBODY-format and do scaling = 7: input through Tree-Format and do scaling = 8: input through Starlab-format and do Scaling = 9: input through NBODY-format but ignore mass (first column) and use IMF based on KZ(20), then do scaling = 10: input through NBODY-format and all units are astrophysical units (mass: M⊙; position: pc; velocity: km/s)",
    23: "Removal of escapers (escape.F) = 0, ≥ 5: no removal of escapers ≥ 1: remove escapers, and ghost particles generated by stellar evolution or two star coalescence (collision) = 2, 3, 4: write escaper diagnostics in esc.11 and escbin.31 for binary systems. = 3: tidal cutoff escape criterion (this option has been misused for tidal tail for a while) = 4: escape angles in main output ≥ 5: initialization & integration of tidal tail (was wrongly: ≥ 3)",
    24: "=1: should not be used anymore, not supported (was: subsystems and IMBH) =2: start with only black holes at T=0.",
    25: "Velocity kicks for white dwarfs (kick.F) = 1: Type 10 Helium white dwarf & 11 Carbon-Oxygen white dwarf = 2: All WDs (type 10, 11 and type 12 Oxygen-Neon white dwarf)",
    26: "Slow-down of two-body motion, increase the regularization integration efficiency ≥ 1: Apply to KS binary ≥ 2: Apply to chain = 3: Rectify to get better energy conservation",
    27: "Two-body tidal circularization (Mardling & Aarseth, 2001; Portegies Zwart et al. 1997) (for values 1,2) plus orbit shrinking of relativistic compact binaries (Rizzuto et al. 2021, 2022; Arca Sedda et al. 2021 (for values 3,4). (Please suppress in KS parallel version) = 1: sequential = 2: chaos = 3: GR energy loss with sequential tides = 4: GR energy loss with chaos tides = −1: Only detect collision and suppress coalescence",
    28: "Magnetic braking. Gravitational radiation for NS or BH binaries is diabled here, since it is treated with KZ(27) now.. ≥ 1: magnetic braking for NS & BH (brake.f, brake3.f) ≥ 2: Diagnostics at main output (brake.f) = 3: Input of ZMH = 1/SQRT(2*N) (Need KZ(5)≥6) (setup.F) = 4: Set every star as type 13 Neutron star (Need KZ(27)=3) (instar.f)",
    29: "(Reserved for new pulsar treatment decisions, not yet used)",
    30: "Hierarchical system regularization = −1: Use chain only = 0: No triple, quad and chain regularization, only merger = 1: Use triple, quad and chain (impact.f) ≥ 2: Diagnostics at begin/end of chain at main output ≥ 3: Diagnostics at each step of chain at main output",
    31: "Centre of mass correction after energy check (cmcorr.f)",
    32: "Adjustment (increase) of adjust interval DTADJ, output interval DELTAT and energy error criterion QE based on binding eneryg of cluster (check.f)",
    33: "Block-step statistics at main output (diagnostics) ≥ 1: Output irregular block step; and K.S. binary step if KZ(8)>0 ≥ 2: Output regular block step",
    34: "Roche-lobe overflow = 1: Roche & Spin synchronisation on binary with circular orbit (synch.f) = 2: Roche & Tidal synchronisation on binary with circular orbit by BSE method (bsetid.f)",
    35: "TIME reset to zero every 100 time units, total time is TTOT = TIME + TOFF (offset.f).",
    36: "Step reduction for hierarchical systems (suppressed).",
    37: "Neighbour list additions (checkl.F) ≥ 1: Add high-velocity particles into neighbor list ≥ 2: Add small time step particle (like close encounter particles near neighbor radius) into neighbor list",
    38: "Force polynomial corrections during regular block step calculation = 0: no corrections = 1: all gains & losses included = 2: small regular force change skipped = 3: fast neighbour loss only",
    39: "Neighbor radius adjustment method = 0: The system has unique density centre and smooth density profile = 1, ≥ 3: The system has no unique density centre or smooth density profile skip velocity modification of RS(I) (regint.f, regcor_gpu.f) do not reduce neighbor radius if particle is outside half mass radius reduce RS(I) by multiply 0.9 instead of estimation of RS(I) based on NNBOPT/NNB when neighbor list overflow happens (fpoly0.F, util_gpu.F) = 2, 3: Consider sqrt(particle mass / average mass) as the factor to determine the particle’s neighbor membership. (fpoly0.F, util_gpu.F) (Important to use if GPU is used for regular forces and neighbour lists!)",
    40: "= 0: For the initialization of particle time steps, use only force and its first derivative to estimate. This is very efficent. > 0: Use fpoly2 (second and third order force derivatives calculation) to estimate the initial time steps. This method provides more accurate initial (only) time steps and avoid incorrent time steps for some special cases like initially cold systems, but the computing cost (initial model only) is much higher (O(N2))",
    41: "proto-star evolution of eccentricity and period for primordial binaries initialization (proto_star_evol, binpop.F)",
    42: "Initial binary distribution = 0: RANGE>0: uniform distribution in log(semi) between SEMI0 and SEMI0/RANGE RANGE<0: uniform distribution in semi between SEMI0 and -1*RANGE. = 1: linearly increasing distribution function f = 0.03438 ∗ logP = 2: f = 3.5logP/[100 + (logP) ∗ ∗2] = 3: f = 2.3(logP − 1)/[45 + (logP − 1) ∗ ∗2]; This is a “3rd” iteration when pre-ms evolution is taken into account with KZ(41)=1 = 4: f = 2.5(logP − 1)/[45 + (logP − 1) ∗ ∗2]; This is a “34th” iteration when pre-ms evolution is taken into account with KZ(41)=1 and RBAR<1.5 = 5: Duquennoy & Mayor 1991, Gaussian distribution with mean log P = 4.8, SDEV in log P = 2.3. Use Num.Recipes routine gasdev.f to obtain random deviates given “idum1”",
    43: "(Unused)",
    44: "(Unused)",
    45: "> 0: Computation of Moments of Inertia (with Chr. Theis) in output listing (ellan.f)",
    46: "HDF5/BINARY/ANSI format output and global parameter output (main output, see chapter 13 for details) = 1, 3: HDF5(if HDF5 is compiled)/BINARY format = 2, 4: ANSI format = 1, 2: Only output active stars with time interval defined by KZ(47) = 3, 4: Output full particle list with time interval defined by KZ(47)",
    47: "Frequency for KZ(46) output. Should be non-negative integer. Output data with time interval 0.5^KZ(47) × SMAX",
    48: "= 0, 1: if 1 reduced HDF5 output (no 2nd and 3rd derivatives of force); warning: if KZ(40)=0 initial values wrong, undefined",
    49: "was used for ellan.f call in output, changed to KZ(45)",
    50: "For unperted KS binary. The neighbor list is searched for finding next KS step. It is safer to get correct step but not efficient when unperted binary number is large. To suppress this, set to 1",
}

_NBODY6PPGPU_KZ = {
    1: _NBODY6PPGPU_BEIJING_KZ[1],
    2: _NBODY6PPGPU_BEIJING_KZ[2],
    3: _NBODY6PPGPU_BEIJING_KZ[3],
    4: _NBODY6PPGPU_BEIJING_KZ[4],
    5: _NBODY6PPGPU_BEIJING_KZ[5],
    6: _NBODY6PPGPU_BEIJING_KZ[6],
    7: _NBODY6PPGPU_BEIJING_KZ[7],
    8: _NBODY6PPGPU_BEIJING_KZ[8],
    9: _NBODY6PPGPU_BEIJING_KZ[9],
    10: _NBODY6PPGPU_BEIJING_KZ[10],
    11: _NBODY6PPGPU_BEIJING_KZ[11],
    12: _NBODY6PPGPU_BEIJING_KZ[12],
    13: _NBODY6PPGPU_BEIJING_KZ[13],
    14: _NBODY6PPGPU_BEIJING_KZ[14],
    15: _NBODY6PPGPU_BEIJING_KZ[15],
    16: _NBODY6PPGPU_BEIJING_KZ[16],
    17: _NBODY6PPGPU_BEIJING_KZ[17],
    18: _NBODY6PPGPU_BEIJING_KZ[18],
    19: "Stellar evolution mass loss. = 0: if KZ(12)= −1, the output data will keep the input data unit if KZ(22)= 2 − 4 or N-body units if KZ(22)= 6 − 10 = 1, 2: supernova scheme ≥ 3: Eggleton, Tout & Hurley ≥ 5: extra diagnostics (mdot.F) = 2, 4: Input stellar parameters from fort.21 (instar.f) N lines of (MI, KW, M0, EPOCH1, OSPIN) MI: Current mass KW: Kstar type M0: Initial mass EPOCH1: evolved age of star (Age = TIME[Myr] − EPOCH1) OSPIN: angular velocity of star",
    20: _NBODY6PPGPU_BEIJING_KZ[20],
    21: _NBODY6PPGPU_BEIJING_KZ[21],
    22: _NBODY6PPGPU_BEIJING_KZ[22],
    23: "Removal of escapers (escape.F) ≥ 1: remove escapers and ghost particles generated by two star coalescence (collision) = 2, 4: write escaper diagnostics in esc 11 ≥ 3: initialization & integration of tidal tail",
    24: "Initial conditions for subsystems < 0: ZMH & RCUT (N-body units) Zhao model (Need KZ(5)≥6, setup.F) = 1: Add one massive black hole (extra input: mass, position, velocity and output frequency), will output black hole data in mbh.45 and its neighbor data in mbhnb.46",
    25: _NBODY6PPGPU_BEIJING_KZ[25],
    26: _NBODY6PPGPU_BEIJING_KZ[26],
    27: "Two-body tidal circularization (Mardling & Aarseth, 2001; Portegies Zwart et al. 1997) (Please suppress in KS parallel version) = 1: sequential = 2: chaos = −1: Only detect collision and suppress coalescence",
    28: "Magnetic braking and gravitational radiation for NS or BH binaries (Need KZ(19)=3) ≥ 1: GR coalescence for NS & BH (brake.f, brake3.f) ≥ 2: Diagnostics at main output (brake.f) = 3: Input of ZMH = 1/SQRT(2*N) (Need KZ(5)≥6) (setup.F) = 4: Set every star as type 13 Neutron star (instar.f)",
    29: "(Suppressed) Boundary reflection for hot system",
    30: _NBODY6PPGPU_BEIJING_KZ[30],
    31: _NBODY6PPGPU_BEIJING_KZ[31],
    32: _NBODY6PPGPU_BEIJING_KZ[32],
    33: _NBODY6PPGPU_BEIJING_KZ[33],
    34: _NBODY6PPGPU_BEIJING_KZ[34],
    35: _NBODY6PPGPU_BEIJING_KZ[35],
    36: _NBODY6PPGPU_BEIJING_KZ[36],
    37: _NBODY6PPGPU_BEIJING_KZ[37],
    38: _NBODY6PPGPU_BEIJING_KZ[38],
    39: _NBODY6PPGPU_BEIJING_KZ[39],
    40: _NBODY6PPGPU_BEIJING_KZ[40],
    41: _NBODY6PPGPU_BEIJING_KZ[41],
    42: _NBODY6PPGPU_BEIJING_KZ[42],
    43: _NBODY6PPGPU_BEIJING_KZ[43],
    44: _NBODY6PPGPU_BEIJING_KZ[44],
    45: "(Unused)",
    46: _NBODY6PPGPU_BEIJING_KZ[46],
    47: _NBODY6PPGPU_BEIJING_KZ[47],
    48: "(Unused)",
    49: "Computation of Moments of Inertia (with Chr. Theis) in fort.60 (ellan.f)",
    50: _NBODY6PPGPU_BEIJING_KZ[50],
}

_NBODY4_KZ = {
    1: "COMMON save on unit 1 at end of run (=2: every 100*NMAX steps).",
    2: "COMMON save on unit 2 at output (=1); restart if DE/E > 5*QE (=2).",
    3: "Basic data on unit 3 at output (freq. NFIX; >1: cluster + tail).",
    4: "Binary diagnostics on unit 4 (# threshold levels = KZ(4) < 10).",
    5: "Initial conditions (#22 =0; =0: uniform & isotropic sphere; =1: Plummer; =2: two Plummer models in orbit, extra input; =3: massive perturber and planetesimal disk, extra input; =4: massive initial binary, extra input; output on unit 35).",
    6: "Output of significant & regularized binaries (=1, 2, 3 & 4).",
    7: "Lagrangian radii (>0: RSCALE; =2, 3, 4: output units 6, 7, 12; >=5: density & rms velocity at given radii on unit 26 & 27; >=5: average mass at given radii on unit 36 every DELTAT; =6: Lagrangian radii for two mass groups on unit 31 & 32).",
    8: "Primordial binaries (=1 & >=3; >0: BINOUT; >2: BINDAT; >3: HIDAT).",
    9: "Individual bodies printed at output time (MIN(5**KZ9,NTOT)).",
    10: "Diagnostic KS output (>0: begin; >1: end; >=3: each step).",
    11: "Synchronization of circular orbits (suppressed).",
    12: "Disk shocks (=1: standard model) or interstellar clouds (< 0).",
    13: "Scaling of time (1: variable by t_cr; 2: variable by t_r; -1: constant scaling to t_r; -2: constant scaling to t_c).",
    14: "External force (=1: linearized; -1: cutoff; =2: point-mass galaxy; =3: point-mass + disk + logarithmic halo in any combination).",
    15: "Triple, quad, chain (#30 > 0) or merger search (>1: full output).",
    16: "Updating of regularization parameters (RMIN, DTMIN & ECLOSE).",
    17: "Modification of ETA (>=1) & ETAU (>1) by tolerance QE.",
    18: "Hierarchical systems (=1: diagnostics; =2: primordial; =3: both).",
    19: "Stellar evolution and mass loss (=1: old supernova scheme; =3: Eggleton, Tout & Hurley; >4: Chernoff--Weinberg).",
    20: "Initial mass function (=0,1: Salpeter; >1: various, see IMF).",
    21: "Extra output (>0: model, etc; >1: CENTRE; >2: MTRACE; >3: GLOBAL).",
    22: "Initial conditions on unit 10 (=1: output; =2,3(unscaled): input).",
    23: "Escaper removal (>1: diagnostics in file ESC; =2: angles unit #6; >1: tidal tails output if #14 = 3).",
    24: "Initial conditions for subsystem (routine SCALE; KZ(24) = #).",
    25: "HR diagnostics of evolving stars (output of B & S on #82 & 83).",
    26: "Slow-down of two-body motion (=1: KS binary; =2: chain binary).",
    27: "Two-body interactions (-2: RADIUS = 0; -1: collision detection; =1: sequential circ; > 0: collision).",
    28: "(not used).",
    29: "Boundary reflection for hot system (suppressed).",
    30: "Chain regularization (=1: basic; >1: main output; >2: each step).",
    31: "Centre of mass correction after energy check.",
    32: "Increase of output intervals (based on single particle energy).",
    33: "Block-step diagnostics at main output (=2: active pipes).",
    34: "Roche lobe overflow (suppressed).",
    35: "Time offset (global time from TTOT = TIME + DTOFF; offset = 100).",
    36: "Step reduction for hierarchical systems (not recommended).",
    37: "Step reduction for encounters with high-velocity particles.",
    38: "Multiple use of GRAPE-6 (sleep 1 sec after each timer check).",
    39: "Neighbour list (=-1: on host; =0: full list or closest on GRAPE).",
    40: "(not used).",
}

_NBODY6_PARAMETERS = {
    "KSTART": "Control index (1: new run; >1: restart; 3, 4, 5: new params).",
    "TCOMP": "Maximum CPU time in minutes (saved in CPU).",
    "N": "Number of objects (N_s + 2*N_b; singles + 3*NBIN0 < NMAX).",
    "NFIX": "Output frequency of data save or binaries (options 3 & 6).",
    "NCRIT": "Final particle number (alternative termination criterion).",
    "NRAND": "Random number sequence skip.",
    "NNBMAX": "Maximum number of neighbours (< LMAX - 5).",
    "NRUN": "Run identification index.",
    "ETAI": "Time-step parameter for irregular force polynomial.",
    "ETAR": "Time-step parameter for regular force polynomial.",
    "RS0": "Initial radius of neighbour sphere (N-body units).",
    "DTADJ": "Time interval for parameter adjustment (N-body units).",
    "DELTAT": "Output time interval (N-body units).",
    "TCRIT": "Termination time (N-body units).",
    "QE": "Energy tolerance (restart if DE/E > 5*QE & KZ(2) > 1).",
    "RBAR": "Virial cluster radius in pc (set = 1 for isolated cluster).",
    "ZMBAR": "Mean mass in solar units (=1.0 if 0; final depends on #20).",
    "DTMIN": "Time-step criterion for regularization search.",
    "RMIN": "Distance criterion for regularization search.",
    "ETAU": "Regularized time-step parameter (6.28/ETAU steps/orbit).",
    "ECLOSE": "Binding energy per unit mass for hard binary (positive).",
    "GMIN": "Relative two-body perturbation for unperturbed motion.",
    "GMAX": "Secondary termination parameter for soft KS binaries.",
    "ALPHA": "Power-law index for initial mass function (used if #20 < 2).",
    "BODY1": "Maximum particle mass before scaling (KZ(20): solar mass).",
    "BODYN": "Minimum particle mass before scaling.",
    "NBIN0": "Number of primordial binaries (for IMF2 with KZ(20) > 1).",
    "NHI0": "Primordial hierarchies (may be needed in IMF if > 0).",
    "ZMET": "Metal abundance (in range 0.03 - 0.0001).",
    "EPOCH0": "Evolutionary epoch (in 10**6 yrs; NB! < 0 for PM evolution).",
    "DTPLOT": "Plotting interval for HRDIAG (N-body units; >= DELTAT).",
    "Q": "Virial ratio (Q = 0.5 for equilibrium).",
    "VXROT": "XY-velocity scaling factor (> 0 for solid-body rotation).",
    "VZROT": "Z-velocity scaling factor (not used if VXROT = 0).",
    "RTIDE": "Unscaled tidal radius (#14 >= 2; otherwise copied to RSPH2).",
    "SMAX": "Maximum time-step (factor of 2 commensurate with 1.0).",
}

_NBODY6PPGPU_PARAMETERS = {
    "KSTART": "=1: new run (construct new model or read from dat.10) =2: restart/continuation of a run, needs comm.1",
    "TCOMP": "Maximum wall-clock time in seconds (parallel runs: wall clock)",
    "TCRTP0": "Termination time in Myr",
    "isernb": "For MPI parallel runs: only irregular block sizes larger than this value are executed in parallel mode (dummy variable for single CPU)",
    "iserreg": "For MPI parallel runs: only regular block sizes larger than this value are executed in parallel mode (dummy variable for single CPU)",
    "iserks": "For MPI parallel runs: only ks block sizes larger than this value are executed in parallel mode (dummy variable for single CPU)",
    "N": "Total number of particles (single + c.m.s. of binaries; singles + 3×c.m.s. of binaries < NMAX−2)",
    "NFIX": "Multiplicator for output interval of data on conf.3 and of data for binary stars (output each DELTAT×NFIX time steps; compare KZ(3) and KZ(6)",
    "NCRIT": "Termination criterion if particle number drops below this value",
    "NRAND": "Random number seed, any positive integer",
    "NNBOPT": "Desired optimal neighbour number (< LMAX−5)",
    "NRUN": "Run identification number",
    "NCOMM": "Multiplicator for frequency to store the dumping data (mydump); positive integer; basic frequency determined by DELTAT",
    "ETAI": "Time-step parameter for irregular force polynomial.",
    "ETAR": "Time-step parameter for regular force polynomial.",
    "RS0": "Initial radius of neighbour sphere (N-body units).",
    "DTADJ": "Time interval for parameter adjustment and energy checks (N-body units).",
    "DELTAT": "Time interval for writing output data and diagnostics, multiplied by NFIX (N–body units)",
    "TCRIT": "Termination time (N-body units).",
    "QE": "Energy tolerance: – immediate termination if DE/E > 5*QE & KZ(2) ≤ 1; – restart if DE/E > 5*QE & KZ(2) > 1 and termination after second restart attempt.",
    "RBAR": "Scaling unit in pc for distance (N–body units).",
    "ZMBAR": "Scaling unit for average particle mass in solar masses (in scale-free simulations RBAR and ZMBAR can be set to zero; depends on KZ(20))",
    "DTMIN": "Time-step criterion for regularization search.",
    "RMIN": "Distance criterion for regularization search.",
    "ETAU": "Regularized time-step parameter (6.28/ETAU steps/orbit).",
    "ECLOSE": "Binding energy per unit mass for hard binary (positive).",
    "GMIN": "Relative two-body perturbation for unperturbed motion.",
    "GMAX": "Secondary termination parameter for soft KS binaries.",
    "SMAX": "Maximum time-step (factor of 2 commensurate with 1.0).",
    "LEVEL": "Stellar Evolution Level (see Kamlah et al. 2022), new input element &INSSE, &INBSE, &INCOLL: new NAMELIST blocks read after LEVEL by subroutine READSE, called from input.F; if blocks are empty in input, defaults according to LEVEL taken.",
    "ALPHAS": "Power-law index for initial mass function, routine data.F",
    "BODY1": "Maximum particle mass before scaling (KZ(20): solar mass).",
    "BODYN": "Minimum particle mass before scaling.",
    "NBIN0": "Number of primordial binaries (need KZ(8)>0) – by routine imf2.F using a binary IMF (KZ(20)≥2) – by routine binpop.F splitting single stars (KZ(8)>0) – by reading subsystems from dat.10 (KZ(22)≥2)",
    "NHI0": "Number of primordial hierarchical systems (need KZ(18)≥2)",
    "ZMET": "Metal abundance (in range 0.03 - 0.0001).",
    "EPOCH0": "Formation time of stellar population, should be ≤ 0, since at time of simulation start the stellar AGE is -EPOCH0 (in 10^6 yrs); note that datsev.21 allows to input individual  stellar ages",
    "DTPLOT": "Plotting interval for HRDIAG (N-body units; >= DELTAT).",
    "Q": "Virial ratio (Q = 0.5 for equilibrium).",
    "VXROT": "XY-velocity scaling factor (> 0 for solid-body rotation).",
    "VZROT": "Z-velocity scaling factor (not used if VXROT = 0).",
    "RTIDE": "Unscaled tidal radius for KZ(14)=2 and KZ(22)≥2. If not zero, RBAR = RT/RTIDE where RT[pc] is tidal radius calculated from input GMG and RG0",
}

_NBODY4_PARAMETERS = {
    "KSTART": "Control index (1: new run; >1: restart; 3, 4, 5: new params).",
    "TCOMP": "Maximum CPU time in minutes (saved in CPU).",
    "GPID": "Number of boards (counting from 0).",
    "N": "Number of objects (N_s + 2*N_b; singles + 3*NBIN0 < NMAX).",
    "NFIX": "Output frequency of data save or binaries (options 3 & 6).",
    "NCRIT": "Final particle number (alternative termination criterion).",
    "NRAND": "Random number sequence skip.",
    "NRUN": "Run identification index.",
    "ETA": "Time-step parameter for total force polynomial.",
    "DTADJ": "Time interval for parameter adjustment (N-body units).",
    "DELTAT": "Output time interval (N-body units).",
    "TCRIT": "Termination time (N-body units).",
    "QE": "Energy tolerance (restart if DE/E > 5*QE & KZ(2) > 1).",
    "RBAR": "Virial cluster radius in pc (set = 1 for isolated cluster).",
    "ZMBAR": "Mean mass in solar units (=1.0 if 0; final depends on #20).",
    "DTMIN": "Time-step criterion for regularization search.",
    "RMIN": "Distance criterion for regularization search.",
    "ETAU": "Regularized time-step parameter (6.28/ETAU steps/orbit).",
    "ECLOSE": "Binding energy per unit mass for hard binary (positive).",
    "GMIN": "Relative two-body perturbation for unperturbed motion.",
    "GMAX": "Secondary termination parameter for soft KS binaries.",
    "ALPHA": "Power-law index for initial mass function (used if #20 < 2).",
    "BODY1": "Maximum particle mass before scaling (KZ(20): solar mass).",
    "BODYN": "Minimum particle mass before scaling.",
    "NBIN0": "Number of primordial binaries (for IMF2 with KZ(20) > 1).",
    "ZMET": "Metal abundance (in range 0.03 - 0.0001).",
    "EPOCH0": "Evolutionary epoch (in 10**6 yrs; NB! < 0 for PM evolution).",
    "DTPLOT": "Plotting interval for HRDIAG (N-body units; >= DELTAT).",
    "Q": "Virial ratio (Q = 0.5 for equilibrium).",
    "VXROT": "XY-velocity scaling factor (> 0 for solid-body rotation).",
    "VZROT": "Z-velocity scaling factor (not used if VXROT = 0).",
    "RTIDE": "Unscaled tidal radius (#14 >= 2; otherwise copied to RSPH2).",
}
