"""Configs for NbodyX codes."""

_NBODY6_CONFIG = {
    1: "COMMON save unit 1 (=1: 'touch STOP'; =2: every 100*NMAX steps).",
    2: "COMMON save unit 2 (=1: at output; =2: restart if DE/E > 5*QE).",
    3: "Basic data unit 3 at output time (unformatted, frequency NFIX; =1/2: standard and tail; =3: tail only; >3: cluster + tail).",
    4: "Binary diagnostics on unit 4 (# threshold levels = KZ(4) < 10); (suppressed in input.f & ksint.f); new usage: number of NS & BH on unit #4; >1: BH mass histogram.",
    5: "Initial conditions (#22 =0; =0: uniform & isotropic sphere); =1: Plummer; =2: two Plummer models in orbit, extra input; =3: massive perturber and planetesimal disk, extra input; =4: massive initial binary, extra input: A, E, M1, M2; =5: Jaffe model; >=6: Zhao BH cusp model, extra input if #24 < 0: ZMH, RCUT.",
    6: "Soft & regularized binaries & individual bodies at main output; =1: soft & regularized binaries on unit 6; =2: regularized binaries only; >2: individual bodies (loop from 1 to KZ(6)).",
    7: "Lagrangian radii (>0: RSCALE; =2, 3, 4: output units 6, 7); >=2: half-mass radii of 50% mass, also 1% heavies, unit 6; >=2: Lagrangian radii for two mass groups on unit 31 & 32; >=2: geometric radii for three mass groups on unit 6; =5: density, rms velocity & mean mass on unit 26, 27 & 36; =6: pairwise values of mean mass and radii on unit 28.",
    8: "Primordial binaries (=1 & >=3 routine BINPOP; >=3: SWEEP; =4: Kroupa 1995 period distribution; >4: standard setup using RANGE & SEMI0).",
    9: "Binary output  (=1, 2, 3 in BINDAT): =1: regularized binaries on OUT9; >1: hierarchical systems on HIDAT (NMERGE > 0); =2: regularized and soft binaries (unit #19); =3: soft binaries only on #19.",
    10: "Diagnostic KS output (>0: begin KS; >1: end; >=3: each step).",
    11: "Algorithmic Chain regularization and post-Newtonian (NBODY7). non-zero: PN for unpert KS or re-init ARChain (ksint.f); > 0: addition of initial BHs (binary/singles; scale.f); = -1: standard case of subsystem for ARChain (ksint.f); < -1: ARChain restricted to BH binary components (ksint.f).",
    12: "HR diagnostics of evolving stars (> 0; interval DTPLOT); =2: input of stellar parameters on fort.12 (routine INSTAR).",
    13: "Interstellar clouds (=1: constant velocity; >1: Gaussian).",
    14: "External force (=1: standard tidal field; =2: point-mass galaxy; =3: point-mass + bulge + disk + halo + Plummer; =4: Plummer).",
    15: "Triple, quad, chain (#30 > 0) or merger search (>1: more output).",
    16: "Updating of regularization parameters (>0: RMIN, DTMIN & ECLOSE); >1: RMIN expression based on core radius; >2: modify RMIN for GPERT > 0.05 or < 0.002 in chain.",
    17: "Modification of ETAI, ETAR (>=1) and ETAU (>1) by tolerance QE.",
    18: "Hierarchical systems (=1: diagnostics; =2: primordial; =3: both).",
    19: "Mass loss (=1: old supernova scheme; =3: Eggleton, Tout & Hurley; >3: extra diagnostics).",
    20: "Initial mass function (=0: Salpeter type using ALPHAS; =1: Scalo; =2, 4: Kroupa 1993; =3, 5: Eggleton; > 1: primordial binaries; =6, 7: Kroupa 2001; binary correlated m1/m2, also brown dwarfs. Note: Use PARAMETER (MAXM=1) for setting BODY(1) = BODY10). KGT93 (Kroupa, Gilmore & Tout 1993) not recommended.",
    21: "Extra output (>0: MODEL #, TCOMP, DMIN, AMIN; >1: NESC by JACOBI).",
    22: "Initial m, r, v on #10 (=1: output; >=2: input; >2: no scaling; =2: m, r, v on #10 in any units; scaled to standard units; Note: choose #20 = 0 to avoid Salpeter IMF with scaling; =3: no scaling of input read on fort.10; =4: input from mcluster.c (no scaling; binaries if NBIN0 >0); =-1: astrophysical input (M_sun, km/s, pc) on unit #10).",
    23: "Escaper removal (>1: diagnostics in file ESC with V_inf in km/s); >=3: initialization & integration of tidal tail.",
    24: "Initial conditions for subsystem (M,X,V routine SCALE; KZ(24)= #); <0: ZMH & RCUT (N-body units) Zhao model (#5>=6).",
    25: "Velocity kicks for white dwarfs (=1: type 11 & 12; >1: all WDs).",
    26: "Slow-down of two-body motion (>=1: KS; >=2: chain; =3: rectify).",
    27: "Tidal effects (=1: sequential; =2: chaos; =3: GR energy loss); =-1: collision detector, no coalescence, #13 < 0.",
    28: "GR radiation for NS & BH binaries (with #19 = 3; choice of #27); =4 and #27 = 3: neutron star capture (instar.f).",
    29: "Boundary reflection for hot system (suppressed).",
    30: "Multiple regularization (=1: all; >1: BEGIN/END; >2: each step); =-1: CHAIN only; =-2: TRIPLE & QUAD only.",
    31: "Centre of mass correction after ADJUST (don't use with #23 = 0).",
    32: "Increase output intervals & SMAX based on single particle energy.",
    33: "Histograms at main output (>=1: STEP; =2: STEPR, NBHIST & BINARY).",
    34: "Roche-lobe overflow (=1: ROCHE & SYNCH; =2: ROCHE & BSE synch).",
    35: "Time offset (global time from TTOT = TIME + TOFF; offset = 100).",
    36: "Step reduction for hierarchical systems (suppressed).",
    37: "Neighbour additions in CHECKL (>0: high-velocity; >1: all types).",
    38: "Force polynomial corrections.",
    39: "No unique density centre.",
    40: "Neighbour number control.",
    41: "Pre-mainsequence stellar evolution.",
    42: "Kozai diagnostics.",
    43: "Small velocity kick after GR coalescence.",
    44: "Plotting file for main cluster parameters.",
    45: "Plotting file for BH.",
    46: "Reserved for data analysis.",
    50: "Not used.",
}


_NBODY6GPU_CONFIG = {}

_NBODY4_CONFIG = {
    1: "COMMON save on unit 1 at end of run (=2: every 100*NMAX steps).",
    2: "COMMON save on unit 2 at output (=1); restart if DE/E > 5*QE (=2).",
    3: "Basic data on unit 3 at output (freq. NFIX; >1: cluster + tail).",
    4: "Binary diagnostics on unit 4 (# threshold levels = KZ(4) < 10).",
    5: "Initial conditions (#22 =0; =0: uniform & isotropic sphere; =1: Plummer; =2: two Plummer models in orbit, extra input; =3: massive perturber and planetesimal disk, extra input; =4: massive initial binary, extra input; output on unit 35).",
    6: "Output of significant & regularized binaries (=1, 2, 3 & 4).",
    7: "Lagrangian radii (>0: RSCALE; =2, 3, 4: output units 6, 7, 12; >=5: density & rms velocity at given radii on unit 26 & 27; >=5: average mass at given radii on unit 36 every DELTAT; =6: Lagrangian radii for two mass groups on unit 31 & 32).",
    8: "Primordial binaries (=1 & >=3; >0: BINOUT; >2: BINDAT; >3: HIDAT).",
    9: "Individual bodies printed at output time (MIN(5**KZ9,NTOT)).",
    10: "Diagnostic KS output (>0: begin; >1: end; >=3: each step).",
    11: "Synchronization of circular orbits (suppressed).",
    12: "Disk shocks (=1: standard model) or interstellar clouds (< 0).",
    13: "Scaling of time (1: variable by t_cr; 2: variable by t_r; -1: constant scaling to t_r; -2: constant scaling to t_c).",
    14: "External force (=1: linearized; -1: cutoff; =2: point-mass galaxy; =3: point-mass + disk + logarithmic halo in any combination).",
    15: "Triple, quad, chain (#30 > 0) or merger search (>1: full output).",
    16: "Updating of regularization parameters (RMIN, DTMIN & ECLOSE).",
    17: "Modification of ETA (>=1) & ETAU (>1) by tolerance QE.",
    18: "Hierarchical systems (=1: diagnostics; =2: primordial; =3: both).",
    19: "Stellar evolution and mass loss (=1: old supernova scheme; =3: Eggleton, Tout & Hurley; >4: Chernoff--Weinberg).",
    20: "Initial mass function (=0,1: Salpeter; >1: various, see IMF).",
    21: "Extra output (>0: model, etc; >1: CENTRE; >2: MTRACE; >3: GLOBAL).",
    22: "Initial conditions on unit 10 (=1: output; =2,3(unscaled): input).",
    23: "Escaper removal (>1: diagnostics in file ESC; =2: angles unit #6; >1: tidal tails output if #14 = 3).",
    24: "Initial conditions for subsystem (routine SCALE; KZ(24) = #).",
    25: "HR diagnostics of evolving stars (output of B & S on #82 & 83).",
    26: "Slow-down of two-body motion (=1: KS binary; =2: chain binary).",
    27: "Two-body interactions (-2: RADIUS = 0; -1: collision detection; =1: sequential circ; > 0: collision).",
    28: "(not used).",
    29: "Boundary reflection for hot system (suppressed).",
    30: "Chain regularization (=1: basic; >1: main output; >2: each step).",
    31: "Centre of mass correction after energy check.",
    32: "Increase of output intervals (based on single particle energy).",
    33: "Block-step diagnostics at main output (=2: active pipes).",
    34: "Roche lobe overflow (suppressed).",
    35: "Time offset (global time from TTOT = TIME + DTOFF; offset = 100).",
    36: "Step reduction for hierarchical systems (not recommended).",
    37: "Step reduction for encounters with high-velocity particles.",
    38: "Multiple use of GRAPE-6 (sleep 1 sec after each timer check).",
    39: "Neighbour list (=-1: on host; =0: full list or closest on GRAPE).",
    40: "(not used).",
}
